version: '3.8'
services:
  postgres-db:
    image: postgres:15
    container_name: reactive-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fraud_db

  redis-cache:
    image: redis:7-alpine
    container_name: reactive-redis
    ports:
      - "6379:6379"