version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: reactive-postgres-banking
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_banking
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fraud_db
    volumes:
      # El script se ejecuta automáticamente al iniciar el contenedor por primera vez
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    # --- SECCIÓN DE HEALTHCHECK ---
    healthcheck:
      # pg_isready es una utilidad de Postgres para verificar la conexión
      test: ["CMD-SHELL", "pg_isready -U user_banking -d fraud_db"]
      interval: 10s    # Cada cuánto tiempo hace la prueba
      timeout: 5s      # Cuánto tiempo espera una respuesta antes de fallar
      retries: 5       # Intentos antes de marcar el contenedor como "unhealthy"
      start_period: 5s # Tiempo de gracia inicial para que el motor arranque