apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: banking-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server-container
        image: jchaconv/auth-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000 # Puerto interno que expone tu App de Spring

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: banking-ns
spec:
  type: NodePort
  selector:
    app: auth-server
  ports:
    - protocol: TCP
      port: 9000      # Puerto del servicio (coincide con tu URL de Docker)
      targetPort: 9000 # Hacia d√≥nde redirige en el pod
      nodePort: 30900 # Puerto externo opcional para el cluster