apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-app
  namespace: banking-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
      - name: fraud-detection-container
        image: jchaconv/fraud-detection-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        # IMPORTANTE: Para R2DBC se suele usar SPRING_R2DBC_URL
        - name: SPRING_R2DBC_URL
          value: "r2dbc:postgresql://postgres-service:5432/fraud_db"
        - name: SPRING_R2DBC_USERNAME
          value: "jchacon"
        - name: SPRING_R2DBC_PASSWORD
          value: "banking123"
        # Mantén estas por si acaso tu app usa JDBC para alguna validación
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/fraud_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "jchacon"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "banking123"
        # Redis
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-service"
        # Kafka
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-entrypoint
  namespace: banking-ns
spec:
  type: NodePort
  selector:
    app: fraud-detection
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081