version: '3.8'

services:
  # --- INFRAESTRUCTURA ---
  postgres-db:
    image: postgres:15-alpine
    container_name: reactive-postgres-banking
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_banking
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fraud_db
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_banking -d fraud_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-banking:
    image: redis:latest
    container_name: redis-banking
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s

  kafka-banking:
    image: apache/kafka:3.7.0
    container_name: kafka-banking
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-banking:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-banking:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  # --- MICROSERVICIOS ---
  auth-server:
    build: ./auth-server
    container_name: auth-server
    ports:
      - "9000:9000"
    environment:
      - AUTH_SERVER_ISSUER=http://auth-server:9000

  fraud-detection-service:
    build: ./fraud-detection-service
    container_name: fraud-detection-service
    ports:
      - "8081:8081"
    depends_on:
      postgres-db:
        condition: service_healthy
      kafka-banking:
        condition: service_started
      redis-banking:
        condition: service_healthy
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres-db:5432/fraud_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-banking:9092
      - SPRING_REDIS_HOST=redis-banking
      - JWT_ISSUER_URI=http://auth-server:9000

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      kafka-banking:
        condition: service_started
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-banking:9092